name: Deploy migration and app

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.LAMIN_BUILD_DOCS }}
          repository: "laminlabs/laminapp"
          event-type: deploy
