name: Deploy migration and app

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy lamindata laminapp
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN_DEPLOY_LAMINAPP }}
          repository: "laminlabs/laminapp"
          event-type: deploy
          client-payload: '{"branch": "releases/lamindata/0.1"}'

      - name: Deploy altos laminapp
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN_DEPLOY_LAMINAPP }}
          repository: "laminlabs/laminapp"
          event-type: deploy
          client-payload: '{"branch": "releases/altos"}'
