name: Deploy laminapp REST API for altos

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy laminapp REST API for altos
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN_DEPLOY_LAMINAPP }}
          repository: "laminlabs/laminapp"
          event-type: deploy
          client-payload: '{"branch": "deploy-rest-api-altos"}'
